kind: pipeline
name: RAD KERNEL BUILD OLDCAM

clone:
  disable: true

steps:
- name: oldcam
  image: archlinux:latest
  environment:
      TG_BOT_API:
        from_secret: TG_BOT_API
  commands:
    - "export TG_BOT_API"
    - pacman -Sy base-devel bc llvm curl zip wget git --noconfirm
    - git clone --depth=1 --quiet https://github.com/theradcolor/android_kernel_xiaomi_whyred.git -b ${DRONE_COMMIT_BRANCH} source
    - cd source
    - git clone --depth=1 --quiet https://github.com/theradcolor/lazyscripts.git -b master
    - sed -i "s/BOT_TOKEN=.*/BOT_TOKEN=$TG_BOT_API/g" lazyscripts/ci-scripts/ci-rad
    - script -c "bash -x lazyscripts/ci-scripts/ci-rad --oldcam --gcc" build.log

---
kind: pipeline
name: RAD KERNEL BUILD NEWCAM

clone:
  disable: true

steps:
- name: newcam
  image: archlinux:latest
  environment:
      TG_BOT_API:
        from_secret: TG_BOT_API
  commands:
    - "export TG_BOT_API"
    - pacman -Sy base-devel bc llvm curl zip wget git --noconfirm
    - git clone --depth=1 --quiet https://github.com/theradcolor/android_kernel_xiaomi_whyred.git -b ${DRONE_COMMIT_BRANCH} source
    - cd source
    - git clone --depth=1 --quiet https://github.com/theradcolor/lazyscripts.git -b master
    - sed -i "s/BOT_TOKEN=.*/BOT_TOKEN=$TG_BOT_API/g" lazyscripts/ci-scripts/ci-rad
    - script -c "bash -x lazyscripts/ci-scripts/ci-rad --newcam --gcc" build.log
